Celery : start as init script

diff --git a/nocout/nocout/celerybeat.init b/nocout/nocout/celerybeat.init
--- a/nocout/nocout/celerybeat.init
+++ b/nocout/nocout/celerybeat.init
@@ -1,12 +1,12 @@
-#!/bin/bash
-# =========================================================
+#!/bin/sh
+# ============================================
 #  celerybeat - Starts the Celery periodic task scheduler.
-# =========================================================
+# ============================================
 #
-# :Usage: /etc/init.d/celerybeat {start|stop|force-reload|restart|try-restart|status}
-# :Configuration file: /etc/default/celerybeat or /etc/default/celeryd
+# :Usage: /etc/init.d/celerybeat {start|stop|restart|status}
+# :Configuration file: /etc/sysconfig/celerybeat
 #
-# See http://docs.celeryproject.org/en/latest/tutorials/daemonizing.html#generic-init-scripts
+# See http://docs.celeryproject.org/en/latest/tutorials/daemonizing.html
 
 ### BEGIN INIT INFO
 # Provides:          celerybeat
@@ -14,109 +14,47 @@
 # Required-Stop:     $network $local_fs $remote_fs
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: celery periodic task scheduler
+# Short-Description: celery task worker daemon
 ### END INIT INFO
+#
+#
+# To implement separate init scripts, do NOT copy this script.  Instead,
+# symlink it.  I.e., if my new application, "little-worker" needs an init, I
+# should just use:
+#
+#   ln -s /etc/init.d/celerybeat /etc/init.d/little-worker
+#
+# You can then configure this by manipulating /etc/sysconfig/little-worker.
+#
+# Setting `prog` here allows you to symlink this init script, making it easy
+# to run multiple processes on the system.
 
-# Cannot use set -e/bash -e since the kill -0 command will abort
-# abnormally in the absence of a valid process ID.
-#set -e
-VERSION=10.1
-echo "celery init v${VERSION}."
-
-if [ $(id -u) -ne 0 ]; then
-    echo "Error: This program can only be used by the root user."
-    echo "       Unpriviliged users must use 'celery beat --detach'"
-    exit 1
-fi
-
-
-# May be a runlevel symlink (e.g. S02celeryd)
-if [ -L "$0" ]; then
-    SCRIPT_FILE=$(readlink "$0")
+# If we're invoked via SysV-style runlevel scripts we need to follow the 
+# link from rcX.d before working out the script name.
+if [[ `dirname $0` == /etc/rc*.d ]]; then
+    target="$(readlink $0)"
 else
-    SCRIPT_FILE="$0"
-fi
-SCRIPT_NAME="$(basename "$SCRIPT_FILE")"
-
-# /etc/init.d/celerybeat: start and stop the celery periodic task scheduler daemon.
-
-# Make sure executable configuration script is owned by root
-_config_sanity() {
-    local path="$1"
-    local owner=$(ls -ld "$path" | awk '{print $3}')
-    local iwgrp=$(ls -ld "$path" | cut -b 6)
-    local iwoth=$(ls -ld "$path" | cut -b 9)
-
-    if [ "$(id -u $owner)" != "0" ]; then
-        echo "Error: Config script '$path' must be owned by root!"
-        echo
-        echo "Resolution:"
-        echo "Review the file carefully and make sure it has not been "
-        echo "modified with mailicious intent.  When sure the "
-        echo "script is safe to execute with superuser privileges "
-        echo "you can change ownership of the script:"
-        echo "    $ sudo chown root '$path'"
-        exit 1
-    fi
-
-    if [ "$iwoth" != "-" ]; then  # S_IWOTH
-        echo "Error: Config script '$path' cannot be writable by others!"
-        echo
-        echo "Resolution:"
-        echo "Review the file carefully and make sure it has not been "
-        echo "modified with malicious intent.  When sure the "
-        echo "script is safe to execute with superuser privileges "
-        echo "you can change the scripts permissions:"
-        echo "    $ sudo chmod 640 '$path'"
-        exit 1
-    fi
-    if [ "$iwgrp" != "-" ]; then  # S_IWGRP
-        echo "Error: Config script '$path' cannot be writable by group!"
-        echo
-        echo "Resolution:"
-        echo "Review the file carefully and make sure it has not been "
-        echo "modified with malicious intent.  When sure the "
-        echo "script is safe to execute with superuser privileges "
-        echo "you can change the scripts permissions:"
-        echo "    $ sudo chmod 640 '$path'"
-        exit 1
-    fi
-}
-
-scripts=""
-
-if test -f /etc/default/celeryd; then
-    scripts="/etc/default/celeryd"
-    _config_sanity /etc/default/celeryd
-    . /etc/default/celeryd
+    target=$0
 fi
 
-EXTRA_CONFIG="/etc/default/${SCRIPT_NAME}"
-if test -f "$EXTRA_CONFIG"; then
-    scripts="$scripts, $EXTRA_CONFIG"
-    _config_sanity "$EXTRA_CONFIG"
-    . "$EXTRA_CONFIG"
-fi
+prog="$(basename $target)"
 
-echo "Using configuration: $scripts"
+# Source the centos service helper functions
+source /etc/init.d/functions
+# NOTE: "set -e" does not work with the above functions,
+# which use non-zero return codes as non-error return conditions
 
-CELERY_BIN=${CELERY_BIN:-"celery"}
-DEFAULT_USER="celery"
-DEFAULT_PID_FILE="/var/run/celery/beat.pid"
-DEFAULT_LOG_FILE="/var/log/celery/beat.log"
+# some commands work asyncronously, so we'll wait this many seconds
+SLEEP_SECONDS=5
+
+DEFAULT_PID_FILE="/var/run/celery/$prog.pid"
+DEFAULT_LOG_FILE="/var/log/celery/$prog.log"
 DEFAULT_LOG_LEVEL="INFO"
-DEFAULT_CELERYBEAT="$CELERY_BIN beat"
+DEFAULT_NODES="celery"
 
-CELERYBEAT=${CELERYBEAT:-$DEFAULT_CELERYBEAT}
-CELERYBEAT_LOG_LEVEL=${CELERYBEAT_LOG_LEVEL:-${CELERYBEAT_LOGLEVEL:-$DEFAULT_LOG_LEVEL}}
+CELERY_DEFAULTS=${CELERY_DEFAULTS:-"/etc/sysconfig/$prog"}
 
-# Sets --app argument for CELERY_BIN
-CELERY_APP_ARG=""
-if [ ! -z "$CELERY_APP" ]; then
-    CELERY_APP_ARG="--app=$CELERY_APP"
-fi
-
-CELERYBEAT_USER=${CELERYBEAT_USER:-${CELERYD_USER:-$DEFAULT_USER}}
+test -f "$CELERY_DEFAULTS" && . "$CELERY_DEFAULTS"
 
 # Set CELERY_CREATE_DIRS to always create log/pid dirs.
 CELERY_CREATE_DIRS=${CELERY_CREATE_DIRS:-0}
@@ -131,26 +69,34 @@ if [ -z "$CELERYBEAT_LOG_FILE" ]; then
     CELERY_CREATE_LOGDIR=1
 fi
 
-export CELERY_LOADER
+CELERYBEAT_LOG_LEVEL=${CELERYBEAT_LOG_LEVEL:-${CELERYBEAT_LOGLEVEL:-$DEFAULT_LOG_LEVEL}}
+CELERYBEAT=${CELERYBEAT:-"${CELERY_BIN} beat"}
+CELERYBEAT=${CELERYBEAT:-$DEFAULT_CELERYBEAT}
+CELERYBEAT_NODES=${CELERYBEAT_NODES:-$DEFAULT_NODES}
 
-CELERYBEAT_OPTS="$CELERYBEAT_OPTS -f $CELERYBEAT_LOG_FILE -l $CELERYBEAT_LOG_LEVEL"
+# This is used to change how Celery loads in the configs.  It does not need to
+# be set to be run.
+export CELERY_LOADER
 
 if [ -n "$2" ]; then
     CELERYBEAT_OPTS="$CELERYBEAT_OPTS $2"
 fi
 
+CELERYBEAT_OPTS=${CELERYBEAT_OPTS:-"--app=$CELERY_APP"}
 CELERYBEAT_LOG_DIR=`dirname $CELERYBEAT_LOG_FILE`
 CELERYBEAT_PID_DIR=`dirname $CELERYBEAT_PID_FILE`
 
 # Extra start-stop-daemon options, like user/group.
+if [ -n "$CELERYBEAT_USER" ]; then
+    DAEMON_OPTS="$DAEMON_OPTS --uid=$CELERYBEAT_USER"
+fi
+if [ -n "$CELERYBEAT_GROUP" ]; then
+    DAEMON_OPTS="$DAEMON_OPTS --gid=$CELERYBEAT_GROUP"
+fi
 
-CELERYBEAT_CHDIR=${CELERYBEAT_CHDIR:-$CELERYD_CHDIR}
 if [ -n "$CELERYBEAT_CHDIR" ]; then
     DAEMON_OPTS="$DAEMON_OPTS --workdir=$CELERYBEAT_CHDIR"
 fi
-
-
-export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"
 
 check_dev_null() {
     if [ ! -c /dev/null ]; then
@@ -159,9 +105,10 @@ check_dev_null() {
     fi
 }
 
+
 maybe_die() {
     if [ $? -ne 0 ]; then
-        echo "Exiting: $*"
+        echo "Exiting: $* (errno $?)"
         exit 77  # EX_NOPERM
     fi
 }
@@ -187,6 +134,7 @@ create_default_dir() {
     fi
 }
 
+
 check_paths() {
     if [ $CELERY_CREATE_LOGDIR -eq 1 ]; then
         create_default_dir "$CELERYBEAT_LOG_DIR"
@@ -196,123 +144,96 @@ check_paths() {
     fi
 }
 
-
-create_paths () {
+create_paths() {
     create_default_dir "$CELERYBEAT_LOG_DIR"
     create_default_dir "$CELERYBEAT_PID_DIR"
 }
 
+export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"
 
-wait_pid () {
-    pid=$1
-    forever=1
-    i=0
-    while [ $forever -gt 0 ]; do
-        kill -0 $pid 1>/dev/null 2>&1
-        if [ $? -eq 1 ]; then
-            echo "OK"
-            forever=0
-        else
-            kill -TERM "$pid"
-            i=$((i + 1))
-            if [ $i -gt 60 ]; then
-                echo "ERROR"
-                echo "Timed out while stopping (30s)"
-                forever=0
-            else
-                sleep 0.5
-            fi
-        fi
-    done
+stop() {
+    [[ ! -f "$CELERYBEAT_PID_FILE" ]] && echo "$prog is stopped" && return 0
+ 
+    local one_failed=
+    echo -n $"Stopping $prog: "
+
+    # killproc comes from 'functions' and brings three nice features:
+    #  1. sending TERM, sleeping, then sleeping more if needed, then sending KILL
+    #  2. handling 'success' and 'failure' output
+    #  3. removes stale pid files, if any remain
+    killproc -p "$CELERYBEAT_PID_FILE" -d "$SLEEP_SECONDS" $prog || one_failed=true
+    echo
+
+    [[ "$one_failed" ]] && return 1 || return 0
 }
 
+start() {
+    echo -n $"Starting $prog: "
 
-stop_beat () {
-    echo -n "Stopping ${SCRIPT_NAME}... "
-    if [ -f "$CELERYBEAT_PID_FILE" ]; then
-        wait_pid $(cat "$CELERYBEAT_PID_FILE")
-    else
-        echo "NOT RUNNING"
-    fi
-}
-
-_chuid () {
-    su "$CELERYBEAT_USER" -c "$CELERYBEAT $*"
-}
-
-start_beat () {
-    echo "Starting ${SCRIPT_NAME}..."
-    _chuid $CELERY_APP_ARG $CELERYBEAT_OPTS $DAEMON_OPTS --detach \
-                --pidfile="$CELERYBEAT_PID_FILE"
-}
-
-
-check_status () {
-    local failed=
-    local pid_file=$CELERYBEAT_PID_FILE
-    if [ ! -e $pid_file ]; then
-        echo "${SCRIPT_NAME} is up: no pid file found"
-        failed=true
-    elif [ ! -r $pid_file ]; then
-        echo "${SCRIPT_NAME} is in unknown state, user cannot read pid file."
-        failed=true
-    else
-        local pid=`cat "$pid_file"`
-        local cleaned_pid=`echo "$pid" | sed -e 's/[^0-9]//g'`
-        if [ -z "$pid" ] || [ "$cleaned_pid" != "$pid" ]; then
-            echo "${SCRIPT_NAME}: bad pid file ($pid_file)"
-            failed=true
-        else
-            local failed=
-            kill -0 $pid 2> /dev/null || failed=true
-            if [ "$failed" ]; then
-                echo "${SCRIPT_NAME} (pid $pid) is down, but pid file exists!"
-                failed=true
-            else
-                echo "${SCRIPT_NAME} (pid $pid) is up..."
-            fi
-        fi
+    # If Celery is already running, bail out
+    if [[ -f "$CELERYBEAT_PID_FILE" ]]; then
+        echo -n "$prog is already running. Use 'restart'."
+        failure
+        echo
+        return 1
     fi
 
-    [ "$failed" ] && exit 1 || exit 0
+    $CELERYBEAT $CELERYBEAT_OPTS $DAEMON_OPTS --detach         \
+                         --pidfile="$CELERYBEAT_PID_FILE"      \
+                         --logfile="$CELERYBEAT_LOG_FILE"      \
+                         --loglevel="$CELERYBEAT_LOG_LEVEL"
+
+    if [[ "$?" == "0" ]]; then
+        # Sleep a few seconds to give Celery a chance to initialize itself.
+        # This is useful to prevent scripts following this one from trying to
+        # use Celery (or its pid files) too early.
+        sleep $SLEEP_SECONDS
+        if [[ -f "$CELERYBEAT_PID_FILE" ]]; then
+            success
+            echo
+            return 0
+        else  # celerybeat succeeded but no pid files found
+            failure
+        fi
+    else  # celerybeat did not succeed
+        failure
+    fi
+    echo
+    return 1
 }
 
+check_status() {
+    status -p "$CELERYBEAT_PID_FILE" $"$prog" || return 1
+    return 0
+}
 
 case "$1" in
     start)
         check_dev_null
         check_paths
-        start_beat
+        start
     ;;
+
     stop)
+        check_dev_null
         check_paths
-        stop_beat
+        stop
     ;;
-    reload|force-reload)
-        echo "Use start+stop"
-    ;;
+
     status)
         check_status
     ;;
+
     restart)
-        echo "Restarting celery periodic task scheduler"
-        check_paths
-        stop_beat
-        check_dev_null
-        start_beat
-    ;;
-    create-paths)
-        check_dev_null
-        create_paths
-    ;;
-    check-paths)
         check_dev_null
         check_paths
+        stop && start
     ;;
+
     *)
-        echo "Usage: /etc/init.d/${SCRIPT_NAME} {start|stop|restart|create-paths|status}"
-        exit 64  # EX_USAGE
+        echo "Usage: /etc/init.d/$prog {start|stop|restart|status}"
+        exit 3
     ;;
 esac
 
-exit 0
+exit $?
